name: "Build"

on:
  pull_request:
  push:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell -p elmPackages.elm-format --run "elm-format --validate client"
      - run: |
          nix-shell -p fourmolu -i $(git ls-files '*.hs')
          if [ -z "$(git status --porcelain)" ]; then
            echo "No style errors detected."
          else
            echo "Style errors detected:"
            git --no-pager diff
            exit 1
          fi
      - uses: cachix/cachix-action@v8
        with:
          name: planning-game
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix-build -A client -A server
      - run: nix-build -A docker
